#ifndef AUTOUPDATERUI_GLOBAL_H
#define AUTOUPDATERUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AUTOUPDATERUI_LIBRARY)
#  define AUTOUPDATERUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define AUTOUPDATERUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AUTOUPDATERUI_GLOBAL_H
