#ifndef UPDATECLIENTUI_GLOBAL_H
#define UPDATECLIENTUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPDATECLIENTUI_LIBRARY)
#  define UPDATECLIENTUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPDATECLIENTUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UPDATECLIENTUI_GLOBAL_H
