; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "updateVarsion1.0"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "My company, Inc."
!define PRODUCT_WEB_SITE "http://www.mycompany.com"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\UpdateClientUITestV1.0.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "YourSoftwareLicence.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\UpdateClientUITestV1.0.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "updateVarsion1.0.exe"
InstallDir "$PROGRAMFILES\updateVarsion1.0"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "D3Dcompiler_47.dll"
  SetOutPath "$INSTDIR\iconengines"
  File "iconengines\qsvgicond.dll"
  SetOutPath "$INSTDIR\imageformats"
  File "imageformats\qgifd.dll"
  File "imageformats\qicnsd.dll"
  File "imageformats\qicod.dll"
  File "imageformats\qjpegd.dll"
  File "imageformats\qsvgd.dll"
  File "imageformats\qtgad.dll"
  File "imageformats\qtiffd.dll"
  File "imageformats\qwbmpd.dll"
  File "imageformats\qwebpd.dll"
  SetOutPath "$INSTDIR"
  File "libEGLd.dll"
  File "libGLESV2d.dll"
  File "opengl32sw.dll"
  SetOutPath "$INSTDIR\platforms"
  File "platforms\qwindowsd.dll"
  SetOutPath "$INSTDIR"
  File "Qt5Cored.dll"
  File "Qt5Guid.dll"
  File "Qt5Svgd.dll"
  File "Qt5Widgetsd.dll"
  File "setup.nsi"
  SetOutPath "$INSTDIR\styles"
  File "styles\qwindowsvistastyled.dll"
  SetOutPath "$INSTDIR\translations"
  File "translations\qt_ar.qm"
  File "translations\qt_bg.qm"
  File "translations\qt_ca.qm"
  File "translations\qt_cs.qm"
  File "translations\qt_da.qm"
  File "translations\qt_de.qm"
  File "translations\qt_en.qm"
  File "translations\qt_es.qm"
  File "translations\qt_fi.qm"
  File "translations\qt_fr.qm"
  File "translations\qt_gd.qm"
  File "translations\qt_he.qm"
  File "translations\qt_hu.qm"
  File "translations\qt_it.qm"
  File "translations\qt_ja.qm"
  File "translations\qt_ko.qm"
  File "translations\qt_lv.qm"
  File "translations\qt_pl.qm"
  File "translations\qt_ru.qm"
  File "translations\qt_sk.qm"
  File "translations\qt_uk.qm"
  SetOutPath "$INSTDIR"
  File "UpdateClientUITestV1.0.exe"
  CreateDirectory "$SMPROGRAMS\updateVarsion1.0"
  CreateShortCut "$SMPROGRAMS\updateVarsion1.0\updateVarsion1.0.lnk" "$INSTDIR\UpdateClientUITestV1.0.exe"
  CreateShortCut "$DESKTOP\updateVarsion1.0.lnk" "$INSTDIR\UpdateClientUITestV1.0.exe"
  File "UpdateClientUI_d.dll"
  File "YourSoftwareLicence.txt"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\updateVarsion1.0\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\updateVarsion1.0\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\UpdateClientUITestV1.0.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\UpdateClientUITestV1.0.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\YourSoftwareLicence.txt"
  Delete "$INSTDIR\UpdateClientUI_d.dll"
  Delete "$INSTDIR\UpdateClientUITestV1.0.exe"
  Delete "$INSTDIR\translations\qt_uk.qm"
  Delete "$INSTDIR\translations\qt_sk.qm"
  Delete "$INSTDIR\translations\qt_ru.qm"
  Delete "$INSTDIR\translations\qt_pl.qm"
  Delete "$INSTDIR\translations\qt_lv.qm"
  Delete "$INSTDIR\translations\qt_ko.qm"
  Delete "$INSTDIR\translations\qt_ja.qm"
  Delete "$INSTDIR\translations\qt_it.qm"
  Delete "$INSTDIR\translations\qt_hu.qm"
  Delete "$INSTDIR\translations\qt_he.qm"
  Delete "$INSTDIR\translations\qt_gd.qm"
  Delete "$INSTDIR\translations\qt_fr.qm"
  Delete "$INSTDIR\translations\qt_fi.qm"
  Delete "$INSTDIR\translations\qt_es.qm"
  Delete "$INSTDIR\translations\qt_en.qm"
  Delete "$INSTDIR\translations\qt_de.qm"
  Delete "$INSTDIR\translations\qt_da.qm"
  Delete "$INSTDIR\translations\qt_cs.qm"
  Delete "$INSTDIR\translations\qt_ca.qm"
  Delete "$INSTDIR\translations\qt_bg.qm"
  Delete "$INSTDIR\translations\qt_ar.qm"
  Delete "$INSTDIR\styles\qwindowsvistastyled.dll"
  Delete "$INSTDIR\setup.nsi"
  Delete "$INSTDIR\Qt5Widgetsd.dll"
  Delete "$INSTDIR\Qt5Svgd.dll"
  Delete "$INSTDIR\Qt5Guid.dll"
  Delete "$INSTDIR\Qt5Cored.dll"
  Delete "$INSTDIR\platforms\qwindowsd.dll"
  Delete "$INSTDIR\opengl32sw.dll"
  Delete "$INSTDIR\libGLESV2d.dll"
  Delete "$INSTDIR\libEGLd.dll"
  Delete "$INSTDIR\imageformats\qwebpd.dll"
  Delete "$INSTDIR\imageformats\qwbmpd.dll"
  Delete "$INSTDIR\imageformats\qtiffd.dll"
  Delete "$INSTDIR\imageformats\qtgad.dll"
  Delete "$INSTDIR\imageformats\qsvgd.dll"
  Delete "$INSTDIR\imageformats\qjpegd.dll"
  Delete "$INSTDIR\imageformats\qicod.dll"
  Delete "$INSTDIR\imageformats\qicnsd.dll"
  Delete "$INSTDIR\imageformats\qgifd.dll"
  Delete "$INSTDIR\iconengines\qsvgicond.dll"
  Delete "$INSTDIR\D3Dcompiler_47.dll"

  Delete "$SMPROGRAMS\updateVarsion1.0\Uninstall.lnk"
  Delete "$SMPROGRAMS\updateVarsion1.0\Website.lnk"
  Delete "$DESKTOP\updateVarsion1.0.lnk"
  Delete "$SMPROGRAMS\updateVarsion1.0\updateVarsion1.0.lnk"

  RMDir "$SMPROGRAMS\updateVarsion1.0"
  RMDir "$INSTDIR\translations"
  RMDir "$INSTDIR\styles"
  RMDir "$INSTDIR\platforms"
  RMDir "$INSTDIR\imageformats"
  RMDir "$INSTDIR\iconengines"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd